#!/bin/bash

NVIDIA_SETTINGS="--gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864"

docker stop music
docker rm music

docker run -d \
    $NVIDIA_SETTINGS \
    --restart=unless-stopped \
    --name=music \
    --publish 80:8000 \
    -v ./mount/music:/app/static/music \
    music
